spring:
  application:
    name: HelloApplication


server:
  port: 8000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#  instance:
#    hostname: localhost
#    instance-id: ${eureka.instance.hostname}:${server.port}
#    homePageUrl: https://localhost:8761/
