spring:
  application:
    name: HelloApplication


server:
  port: 8010

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true




#开启健康检查（需要spring-boot-starter-actuator依赖）
#  instance:
#    hostname: localhost
#    instance-id: ${eureka.instance.hostname}:${server.port}
#    homePageUrl: https://localhost:8761/
