spring:
  application:
    name: Ivokepplication


server:
  port: 9000
  servlet:
    context-path: /invoke

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#  instance:
#    hostname: localhost
#    instance-id: ${eureka.instance.hostname}:${server.port}
#    homePageUrl: https://localhost:8761/
